EMBEDDING_VECTOR_SIZE = 1536
EMBEDDING_MODEL = "text-embedding-ada-002"
PINECONE_INDEX_NAME = "dreamsdb"

NOVELTY_WEIGHT = 0.4
MARKET_WEIGHT = 0.15
USEFULNESS_WEIGHT = 0.15
IMPLEMENTATION_WEIGHT = 0.15
IMPACT_WEIGHT = 0.15